name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'  # ✅ دقیقاً نسخه‌ای که داری

      - name: Show Flutter version
        run: flutter --version

      - name: Activate Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Run Analyze
        run: melos analyze

      - name: Run Tests
        run: melos test
